@startuml
'https://plantuml.com/sequence-diagram
' 図に表示する要素を定義

actor User as ユーザー
participant Server as サーバー
actor User2 as ユーザー2
actor User3 as ユーザー3

' 処理に連番を自動付与
autonumber

' noteで図の中にコメントを付与
' シングルクォートで図には反映されないコメントを書ける
ユーザー ->サーバー:参加リクエスト
サーバー -->ユーザー:参加レスポンス、ユーザーを表示

ユーザー2 ->サーバー:参加リクエスト
サーバー -->ユーザー2:参加レスポンス、すべてのユーザーを表示
サーバー -->ユーザー:ユーザー２参加レスポンス、ユーザー2を表示

ユーザー3 ->サーバー:参加リクエスト
サーバー -->ユーザー3:参加レスポンス、すべてのユーザーを表示
サーバー -->ユーザー2:ユーザー3参加レスポンス、ユーザー3を表示
サーバー -->ユーザー:ユーザー3参加レスポンス、ユーザー3を表示


' 直線の矢印は ->。直線はリクエストを表す


' 点線の矢印は -->。点線はレスポンスを表す

@enduml