@startuml
'https://plantuml.com/sequence-diagram

actor User as ユーザー
participant Server as サーバー
actor User2 as ユーザー2
actor User3 as ユーザー3

ユーザー ->サーバー:退出リクエスト
サーバー -->ユーザー:退出レスポンス、タイトル等に戻る
サーバー ->ユーザー2:退出通知、ユーザー1を退出
サーバー ->ユーザー3:退出通知、ユーザー1を退出

ユーザー2 ->サーバー:退出リクエスト
サーバー -->ユーザー2:退出レスポンス、タイトル等に戻る
サーバー ->ユーザー3:退出通知、ユーザー2を退出

ユーザー3 ->サーバー:退出リクエスト
サーバー -->ユーザー3:退出レスポンス、タイトル等に戻る

note over サーバー:人数が０のため部屋を閉じる
@enduml